DROP TABLE IF EXISTS [dbo].[MatchRecords]
CREATE TABLE [dbo].[MatchRecords]
(
	[match_id] INT NOT NULL PRIMARY KEY IDENTITY,
	[start_time] DATETIME NULL DEFAULT GETDATE(),
	[end_time] DATETIME NULL DEFAULT GETDATE(),
	[status] TINYINT NOT NULL DEFAULT 0 /*NEW0 INGAME1 END2*/
)